//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class OperationHistory
    {
        public int HistoryID { get; set; }
        public int AutoServiceID { get; set; }
        public Nullable<int> OrderID { get; set; }
        public Nullable<int> SupplyOrderID { get; set; }
        public string OperationType { get; set; }
        public string Details { get; set; }
        public Nullable<System.DateTime> OperationDate { get; set; }
        public decimal BalanceChange { get; set; }
    
        public virtual AutoService AutoService { get; set; }
        public virtual ServiceOrders ServiceOrders { get; set; }
        public virtual SupplyOrders SupplyOrders { get; set; }
    }
}
